### ISSUE TITLE
Invalid JSON token F at position 1

### ISSUE THREAD

**Issue by otavio** [orf/cargo-bloat-action#169]
```
...
##[error]Unexpected token F in JSON at position 1
```

This happens using d3735a726f98f4d03e82ed6f0f50b229ca7c936f

**Comment by orf** [comment]
Can you link me to the build?

**Comment by otavio** [comment]
Sure, it is at https://github.com/UpdateHub/updatehub/pull/286/checks?check_run_id=801598760

**Comment by otavio** [comment]
@orf do you have any idea how to fix this, or to workaround?

**Comment by orf** [comment]
Yep! I’ll have this fixed tomorrow, I have been away from my computer recently.

**Comment by otavio** [comment]
That's awesome. Thanks for all your help.

**Comment by orf** [comment]
Try now @otavio 👍

**Comment by otavio** [comment]
It worked like a charm. Thanks a lot.
