### ISSUE TITLE
Allow to select crate from the workspace

### ISSUE THREAD

**Issue by DarkEld3r** [orf/cargo-bloat-action#179]
There should be a way to select a crate from workspace with multiple crates. Perhaps it is a duplicate of the #145 issue, but I think that this is a slightly different issue.

**Comment by Vrixyz** [comment]
@DarkEld3r You might want to try the new option "exclude_packages" from the just released 1.2.0 version, I believe it should address your issue.

**Comment by DarkEld3r** [comment]
@Vrixyz Thanks, that works great.
