### ISSUE TITLE
Sane handling of non-bin and non-lib crates

### ISSUE THREAD

**Issue by appetrosyan** [orf/cargo-bloat-action#366]
I understand that this action has the dubious convenience of parsing the manifest and adding all the packages that `cargo bloat` wouldn't into the list of packages to process. This is an acceptable (if inefficient) method, but it has a few problems. 

Normally, `cargo bloat` ignores the projects that it can't work with. The action fails and stops. 

Normally you can manually specify the packages (or binaries) for which we need to test for bloat. In this action I have to specify every workspace in the package (which normally outnumber the libraries). Moreover, the syntax is not explained. I expected a sequence to be an acceptable input. 

## Solution

1. Don't fail fast on crates that are not supported. Just skip them
2. Don't try to outsmart `cargo bloat`. 
3. Instead of specifying the `exclude crates` specify included packages.

**Comment by orf** [comment]
Closed due to https://github.com/orf/cargo-bloat-action/issues/367.

Pull requests welcome.
