### ISSUE TITLE
Error: Request failed with status code 404

### ISSUE THREAD

**Issue by Skallwar** [orf/cargo-bloat-action#501]
I would love to use this action. However I'm failing to use it.
See: https://github.com/ks0n/goOSe/actions/runs/4670196537/jobs/8269632922?pr=132

**Comment by Skallwar** [comment]
I got the same error on a different project:
https://github.com/Skallwar/suckit/actions/runs/4670343847/jobs/8269956155?pr=217

**Comment by orf** [comment]
Apologies, this project is currently dead. After #367 i don’t really feel like working on it any more

**Comment by Skallwar** [comment]
I'm just astonished by what I just read... It's absolutely unacceptable to be treated like that.

I fully understand your decision. I wish you the best for your future
